### PR TITLE
Typescript type declarations

### PR DESCRIPTION
**Pull request by JonathanMEdwards**
Not sure how to test this.

### CODE REVIEW

**Comment by JonathanMEdwards** [comment]
I'm thinking that what really needs to be tested is that the manifest is correct, so we would need to build the ohm npm package then install it into a TypeScript package. Seems like a lot of work.
A simpler alternative would be to published the typings as a separate package at DefinitelyTyped, which TypeScript knows how to automatically access.

**Comment by pdubroy** [comment]
I added a small test in 1b014d9, and tweaked the file a bit to get things working. Let me know if something doesn't look right. I don't fully understand the differences between all the different ways to declare/export the top-level `ohm` object, but this allows `import ohm from 'ohm-js'` to work, which seems reasonable to me.

**Comment by pdubroy** [comment]
Also I moved the declarations into `index.d.ts` in the root of the repo, as this seemed to be the standard way to do it from what I can tell.

**Comment by JonathanMEdwards** [comment]
As I worried, this doesn't work once packaged in NPM.
Typescript now fails to load ohm at runtime, although it is happy at compile time. I have no clue how to debug this. Module loading is a complete mystery.
Also, none of the interfaces are exported, but that is easy to fix.

**Comment by JonathanMEdwards** [comment]
Solved it. Also need to tighten up test as it isn't checking for missing declarations. Will submit PT shortly

**Pull request merged**
