### PR TITLE
Modernize Operators Example

### PR DESCRIPTION
**Pull request by rtoal**
Use ES module import/export syntax (type: module in package.json), use spreads instead of concat, and clean up some parameter names.

### CODE REVIEW

**Review by pdubroy — APPROVED** [review]
Woo, thanks Ray!

**Comment by pdubroy** [comment]
Hmmm, tests are failing though, due to the use of `import` and `export`: https://travis-ci.org/github/harc/ohm/builds/751856805#L228. I wonder why `"type": "module"` didn't do the trick?

**Comment by pdubroy** [comment]
Thanks Ray, I merged this in manually along with a fix for the CI issue. Man, using ES modules is still super complicated. The problem here was that ESLint doesn't seem to look at the package.json — it needs to be configured separately to treat modules as ES modules.

**Comment by rtoal** [comment]
Sorry it does not work with Travis. It works on the command line when you do npm test.

**Pull request merged**
