### PR TITLE
Make deferred init works for rollup

### PR DESCRIPTION
**Pull request by megabuz**
I've tried to use `ohm-js` with rollup and I've faced the issue of circular dependency in `pexprs.js`.

Based on specification all imports should be evaluated prior to the body of module doing the importing, so in case when `pexprs` requires bunch of extensions, e.g. `pexprs-allowsSkippingPrecedingSpace`, rollup includes these extensions in the final bundle before `pexprs`. However they depend on `pexprs` and I'm receiving error similar to https://github.com/harc/ohm/issues/185#issuecomment-364246068

In this PR I moved body of `pexprs` to separate file. It should make rollup module ordering work correctly.

### CODE REVIEW

**Comment by megabuz** [comment]
I found several similar problems, I'm trying to fix them

**Comment by megabuz** [comment]
So upon further testing I found that any `require` should be able to execute correctly before module that calls it. 
I moved some deferred inits from `main.js` and `Semantics.js` to separate files to break this order dependency

**Comment by pdubroy** [comment]
@megabuz Thanks for taking this on! Is this PR ready for review? It seems to contain some unrelated changes. Can you trying rebasing your branch onto master?

**Comment by megabuz** [comment]
@pdubroy it is ready to review. 
Could you point out unrelated changes? All changes should be related to breaking circular dependencies

**Comment by pdubroy** [comment]
@megabuz Great! And sorry — my mistake, at a quick glance I thought some of these changes were related to something else.

Thanks again, and I'll try to review this in the next day or two.

**Comment by pdubroy** [comment]
Awesome, thanks for doing this! It looked good to me so I've gone ahead and merged it.

**Comment by pdubroy** [comment]
Just published v16.1.1 which contains these changes.

**Pull request merged**
